#Spring properties
spring:
  application:
    name: cliente_dos
    
  datasource:
    url: jdbc:mysql://localhost:3306/tienda?useSSL=false
    username: root
    password: angel
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  
  thymeleaf:
    cache: false